package edu.brown.cs.jhbgbssg.Game.risk;

public enum RiskMessageType {

  CONNECT, REMOVE, START, JOIN, CREATE, CHANGE, DESTROY, WINNER, LOSER, HANDOUT_CARD, NO_CARDS_LEFT, PREVIOUS_ACTION, VALID_ACTIONS, ERROR;

}
