package edu.brown.cs.jhbgbssg.RiskWorld;

public enum TerritoryEnum {

	ALASKA, ONTARIO, CENTRAL_AMERICA, EASTERN_US, WESTERN_US, GREENLAND,
	NORTHWEST_TERRITORY, ALBERTA, QUEBEC, VENEZUAELA, PERU, BRAZIL, ARGENTINIA,
	NORTH_AFRICA, EGYPT, EAST_AFRICA, CENTRAL_AFRICA, SOUTH_AFRICA, MADAGASCAR, ICELAND,
	GREAT_BRITIAN, WESTERN_EUROPE, NORTHERN_EUROPE, SCANDINAVIA, SOUTHERN_EUROPE,
	RUSSIA, AFGHANISTAN, CHINA, INDIA, IRKUTSK, JAPAN, KAMACHATKA, MIDDLE_EAST,
	MONGOLIA, SIAM, SIBERIA, URAL, YAKUTSK, EASTERN_AUSTRALIA, INDONESIA, NEW_GUINEA,
	WESTERN_AUSTRALIA;
}
